# basic options
title: Info campings
author: Kees
description: Informatie over campings waar we overnacht hebben

# URL to GitHub repo
baseurl: "/camping-info" 
url: "https://prudento-nl.github.io"

#URL: "https://github.com/Prudento-NL/camping-info.git"

# URL to images folder at GitHub repo LET OP het format van de link met de PUNT!
images: "https://prudento-nl.github.io/camping-info/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
